export const dataLineSummary = [
    {
        line: "L1",
        color: "#8884d8",
        status: "Running",
        lastOrder: "AC370",
        currentOrder: "AC380",
        followingOrder: "AC390",
        amountAct: 230,
        amountTgt: 240,
        throughputAct: 500,
        throughputTgt: 510,
        TooltipInfo: {
            job_number: "JOB-20250306-L1",
            product_number: "PROD-5678",
            quantity_kg: 240,
            consumption_kg_k: 25.5,
            pml_target_g_m: 18.75,
            width_mm: 600,
            gusset_mm: 100,
        }
    },
    {
        line: "L2",
        color: "#d88a84",
        status: "Running",
        lastOrder: "BC470",
        currentOrder: "BC480",
        followingOrder: "BC490",
        amountAct: 230,
        amountTgt: 330,
        throughputAct: 510,
        throughputTgt: 500,
        TooltipInfo: {
            job_number: "JOB-20250306-L2",
            product_number: "PROD-7890",
            quantity_kg: 330,
            consumption_kg_k: 27.8,
            pml_target_g_m: 20.25,
            width_mm: 750,
            gusset_mm: 120,
        }
    },
    {
        line: "L3",
        color: "#84d88a",
        status: "Running",
        lastOrder: "DF120",
        currentOrder: "DF130",
        followingOrder: "DF140",
        amountAct: 230,
        amountTgt: 280,
        throughputAct: 500,
        throughputTgt: 510,
        TooltipInfo: {
            job_number: "JOB-20250306-L3",
            product_number: "PROD-1234",
            quantity_kg: 280,
            consumption_kg_k: 22.3,
            pml_target_g_m: 15.5,
            width_mm: 550,
            gusset_mm: 90,
        }
    },
    {
        line: "L4",
        color: "#8ad8d8",
        status: "Stopped",
        lastOrder: "GH210",
        currentOrder: "GH220",
        followingOrder: "GH230",
        amountAct: 230,
        amountTgt: 333,
        throughputAct: 500,
        throughputTgt: 510,
        TooltipInfo: {
            job_number: "JOB-20250306-L4",
            product_number: "PROD-3456",
            quantity_kg: 333,
            consumption_kg_k: 24.1,
            pml_target_g_m: 17.8,
            width_mm: 650,
            gusset_mm: 110,
        }
    },
    {
        line: "L5",
        color: "#d88ad8",
        status: "Running",
        lastOrder: "JK750",
        currentOrder: "JK760",
        followingOrder: "JK770",
        amountAct: 230,
        amountTgt: 500,
        throughputAct: 500,
        throughputTgt: 510,
        TooltipInfo: {
            job_number: "JOB-20250306-L5",
            product_number: "PROD-9012",
            quantity_kg: 500,
            consumption_kg_k: 28.5,
            pml_target_g_m: 22.0,
            width_mm: 800,
            gusset_mm: 130,
        }
    },
    {
        line: "L6",
        color: "#d8d84a",
        status: "Paused",
        lastOrder: "MN540",
        currentOrder: "MN550",
        followingOrder: "MN560",
        amountAct: 230,
        amountTgt: 260,
        throughputAct: 60,
        throughputTgt: 510,
        TooltipInfo: {
            job_number: "JOB-20250306-L6",
            product_number: "PROD-2468",
            quantity_kg: 260,
            consumption_kg_k: 19.8,
            pml_target_g_m: 16.4,
            width_mm: 580,
            gusset_mm: 95,
        }
    },
]