-- CreateTable
CREATE TABLE `t_av_article` (
    `ARTICLE_ARTICLE` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ARTICLE_AVID` VARCHAR(20) NULL,
    `ARTICLE_SYSTEM` INTEGER UNSIGNED NOT NULL,
    `ARTICLE_CODE` INTEGER UNSIGNED NOT NULL,
    `ARTICLE_VALUE` FLOAT NULL,

    PRIMARY KEY (`ARTICLE_ARTICLE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_av_data` (
    `DATA_ORDER` INTEGER UNSIGNED NOT NULL,
    `DATA_CODE` INTEGER UNSIGNED NOT NULL,
    `DATA_VALUE` FLOAT NULL,

    UNIQUE INDEX `DATA_INDEX`(`DATA_ORDER`, `DATA_CODE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_av_order` (
    `ORDER_ORDER` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `ORDER_AVID` VARCHAR(20) NULL,
    `ORDER_POSITION` TINYINT UNSIGNED NULL DEFAULT 0,
    `ORDER_ARTICLE` VARCHAR(20) NULL,
    `ORDER_RECIPE` VARCHAR(20) NULL,
    `ORDER_SYSTEM` INTEGER UNSIGNED NOT NULL,
    `ORDER_EXTRUDER` VARCHAR(10) NULL,
    `ORDER_DATETIME` DATETIME(0) NULL,
    `ORDER_STATUS` TINYINT NOT NULL,

    PRIMARY KEY (`ORDER_ORDER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_av_recipe` (
    `RECIPE_RECIPE` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `RECIPE_REZPNR_UNI` VARCHAR(20) NULL,
    `RECIPE_SCHICHT` VARCHAR(4) NULL,
    `RECIPE_SCHICHT_ANTEIL` DECIMAL(6, 2) NULL,
    `RECIPE_REZPNR_MAT` VARCHAR(20) NULL,
    `RECIPE_COMPONENT` TINYINT UNSIGNED NULL DEFAULT 0,
    `RECIPE_MATERIAL` VARCHAR(25) NULL,
    `RECIPE_MATERIAL_ID` VARCHAR(10) NULL,
    `RECIPE_DICHTE` DECIMAL(6, 3) NULL,
    `RECIPE_MATERIAL_ANTEIL` DECIMAL(6, 2) NULL,
    `RECIPE_ROHSTOFF` TEXT NULL,

    PRIMARY KEY (`RECIPE_RECIPE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_charge` (
    `CHARGE_CHARGE` INTEGER NOT NULL,
    `CHARGE_SHORT` VARCHAR(20) NOT NULL,

    UNIQUE INDEX `IDX_CHARGE_SHORT`(`CHARGE_SHORT`),
    PRIMARY KEY (`CHARGE_CHARGE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_line` (
    `LINE_LINE` MEDIUMINT NOT NULL AUTO_INCREMENT,
    `LINE_ID` MEDIUMINT NOT NULL,
    `LINE_NAME` VARCHAR(30) NOT NULL,
    `LINE_SHORT` VARCHAR(10) NOT NULL DEFAULT 'Mxx',
    `LINE_TYPE` MEDIUMINT NOT NULL DEFAULT 0,
    `LINE_STANDORT` MEDIUMINT NOT NULL DEFAULT 0,
    `LINE_GROUP` MEDIUMINT NOT NULL DEFAULT 0,
    `LINE_NEXT` MEDIUMINT NOT NULL DEFAULT 1,
    `LINE_NDOS` MEDIUMINT NOT NULL DEFAULT 0,
    `LINE_COLOUR` BIGINT NOT NULL DEFAULT 0,
    `LINE_MINTPT` DOUBLE NOT NULL DEFAULT 50,
    `LINE_MAXTPT` DOUBLE NOT NULL DEFAULT 150,
    `LINE_MAXABV` DOUBLE NOT NULL DEFAULT 100,
    `LINE_MINWID` DOUBLE NOT NULL DEFAULT 800,
    `LINE_MAXWID` DOUBLE NOT NULL DEFAULT 1800,

    UNIQUE INDEX `IDX_ID_LINE`(`LINE_ID`),
    INDEX `IDX_LINE_GROUP`(`LINE_GROUP`),
    PRIMARY KEY (`LINE_LINE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_rawcharge` (
    `RAWCHARGE_RAWCHARGE` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `RAWCHARGE_RAWMAT` INTEGER UNSIGNED NOT NULL,
    `RAWCHARGE_RAWITEM` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `RAWCHARGE_DELIVERER` INTEGER UNSIGNED NULL,
    `RAWCHARGE_CHARGENR` VARCHAR(20) NULL,
    `RAWCHARGE_REMARK` VARCHAR(50) NULL,
    `RAWCHARGE_DATIM` DATETIME(0) NOT NULL,
    `RAWCHARGE_AMOUNT` FLOAT NOT NULL,
    `RAWCHARGE_ACTAMOUNT` FLOAT NOT NULL,
    `RAWCHARGE_ATTRIBUTE` TINYINT UNSIGNED NOT NULL,
    `RAWCHARGE_STATE` TINYINT UNSIGNED NOT NULL,
    `RAWCHARGE_PARENT` INTEGER UNSIGNED NOT NULL DEFAULT 0,

    PRIMARY KEY (`RAWCHARGE_RAWCHARGE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_rawitem` (
    `RAWITEM_RAWITEM` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `RAWITEM_RAWMAT` INTEGER UNSIGNED NOT NULL,
    `RAWITEM_PRODUCER` INTEGER UNSIGNED NOT NULL DEFAULT 0,
    `RAWITEM_ARTN` VARCHAR(45) NULL,
    `RAWITEM_SHORT` VARCHAR(20) NULL,
    `RAWITEM_PRICE` FLOAT NULL,

    UNIQUE INDEX `IDX_RAWITEM`(`RAWITEM_RAWMAT`, `RAWITEM_PRODUCER`, `RAWITEM_SHORT`),
    PRIMARY KEY (`RAWITEM_RAWITEM`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_rawmat` (
    `RAWMAT_RAWMAT` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `RAWMAT_NAME` VARCHAR(45) NOT NULL DEFAULT '-',
    `RAWMAT_SHORT` VARCHAR(20) NULL DEFAULT '-',
    `RAWMAT_RAWTYP` INTEGER UNSIGNED NULL DEFAULT 0,
    `RAWMAT_PRODUCER` INTEGER UNSIGNED NULL DEFAULT 0,
    `RAWMAT_DENSITY` DOUBLE NOT NULL DEFAULT 0,
    `RAWMAT_BULKDENS` DOUBLE NOT NULL DEFAULT 0,
    `RAWMAT_MFIVAL` DOUBLE NOT NULL DEFAULT 0,
    `RAWMAT_COLOR` BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `RAWMAT_VIPIDX` INTEGER UNSIGNED NULL,
    `RAWMAT_ARTN` VARCHAR(45) NULL,
    `RAWMAT_NOVIP` BOOLEAN NULL DEFAULT false,

    UNIQUE INDEX `IDX_RAWMAT_SHORT`(`RAWMAT_SHORT`),
    INDEX `IDX_RAWMAT_PRODUCER`(`RAWMAT_PRODUCER`),
    INDEX `IDX_RAWMAT_RAWTYP`(`RAWMAT_RAWTYP`),
    PRIMARY KEY (`RAWMAT_RAWMAT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_rawtyp` (
    `RAWTYP_RAWTYP` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `RAWTYP_SHORT` VARCHAR(10) NOT NULL,
    `RAWTYP_DESC` VARCHAR(50) NULL,

    UNIQUE INDEX `IDX_RAWTYP_SHORT`(`RAWTYP_SHORT`),
    PRIMARY KEY (`RAWTYP_RAWTYP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `t_silo` (
    `SILO_SILO` INTEGER NOT NULL AUTO_INCREMENT,
    `SILO_NAME` VARCHAR(191) NOT NULL,
    `SILO_QUANTITY` INTEGER NOT NULL,
    `SILO_CHARGE` INTEGER UNSIGNED NOT NULL,
    `SILO_CAPACITY` DECIMAL(6, 2) NOT NULL,
    `SILO_CATEGORY` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`SILO_SILO`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `t_silo` ADD CONSTRAINT `t_silo_SILO_CHARGE_fkey` FOREIGN KEY (`SILO_CHARGE`) REFERENCES `t_rawcharge`(`RAWCHARGE_RAWCHARGE`) ON DELETE RESTRICT ON UPDATE CASCADE;
