-- CreateTable
CREATE TABLE `t_bulk` (
    `BULK_BULK` INTEGER NOT NULL AUTO_INCREMENT,
    `BULK_NAME` VARCHAR(191) NOT NULL,
    `BULK_QUANTITY` INTEGER NOT NULL,
    `BULK_CHARGE` INTEGER UNSIGNED NOT NULL,
    `BULK_CAPACITY` DECIMAL(6, 2) NOT NULL,
    `BULK_CATEGORY` VARCHAR(191) NOT NULL,

    INDEX `t_bulk_BULK_CHARGE_fkey`(`BULK_CHARGE`),
    PRIMARY KEY (`BULK_BULK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `t_bulk` ADD CONSTRAINT `t_bulk_BULK_CHARGE_fkey` FOREIGN KEY (`BULK_CHARGE`) REFERENCES `t_rawcharge`(`RAWCHARGE_RAWCHARGE`) ON DELETE RESTRICT ON UPDATE CASCADE;
